version: "3.9"
services:
  web:
    build:
      context: ./
      dockerfile: ./order/Dockerfile
    restart: always
    volumes:
      - .:/usr/src/app/order
    command: npm run start:dev
    ports:
      - "3000:3000"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-local'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_net
  db:
    image: mysql:5.7
    container_name: 'mysql-local'
    restart: always
    environment:
      MYSQL_DATABASE: 'uki'
      MYSQL_USER: 'uki'
      MYSQL_PASSWORD: 'uki123'
      MYSQL_ROOT_PASSWORD: 'uki123'
    ports:
      - '3306:3306'
    expose:
      - '3306'      
    volumes:
      - my-db:/var/lib/mysql
networks:
  rabbitmq_net:
    driver: bridge
volumes:
  my-db: